### ISSUE TITLE
ng-repeat表单,angularjs 1.2.x验证无效，angularjs 1.3.x有效，1.2.x不支持吗?

### ISSUE THREAD

**Issue by chenli1989** [hueitan/angular-validation#139]
angularjs-1.2.x submit提交验证无效

<form name="Form6" id="form6">
            <fieldset>
                <legend>Form (ng-repeat)</legend>
                <label>Required</label>
                <div ng-repeat="a in form6.required">
                    <input type="text" name="emailRequiredOnly{{$index}}" ng-model="a.required" validator="required" message-id="emailRequiredOnly{{$index}}"/>
                    <span id="emailRequiredOnly{{$index}}"></span>
                </div>
                <blockquote ng-non-bindable>
                    In name attribute we have to use {{$index}}
                    <cite>eg. emailRequiredOnly{{$index}}</cite>
                </blockquote>

                <ul class="button-group">
                    <li><button class="button" validation-submit="Form6">Submit</button></li>
                    <li><button class="button alert" validation-reset="Form6">Reset</button></li>
                    <li><button class="button secondary" ng-disabled="!form6.checkValid(Form6)">checkValid = {{ form6.checkValid(Form6) }}</button></li>
                </ul>
                
            </fieldset>
        </form>

<script src="//cdn.bootcss.com/angular.js/1.2.28/angular.min.js"></script>

**Comment by huei90** [comment]
剛我測了一下，1.2.x 支持喔，用法和 1.3.x 的一樣

**Comment by huei90** [comment]
你好，剛剛加上範例了。

**Comment by chenli1989** [comment]
用angularjs 1.2.28测试，ng-repeat表单，三个input循环,在点击提交submit时，只验证提示最后一个input。另两个都没验证提示，重新下载github上的demo换了1.2.28也是一样只验证提示最后一个！

**Comment by chenli1989** [comment]
用angularjs 1.2.28测试，ng-repeat表单，三个input循环,在点击提交submit时，只验证提示最后一个input。另两个都没验证提示，重新下载github上的demo换了1.2.28也是一样只验证提示最后一个！

**Comment by huei90** [comment]
@chenli1989 Thanks for reporting this.
I have found that 1.2.28 is not able to parse {{$index}}, therefore we have to special handle for this bug.

**Comment by huei90** [comment]
Hi @chenli1989 

I found this is the old issue in angularjs 1.2
https://github.com/angular/angular.js/issues/1404

**Comment by obender** [comment]
Is it resolved in some way ? 
or what the exact clue to resolve it , File name, row...? 

It's just not working for me and I need it fixed... so I will fix and commit, only adding stuff as you asked :-)

**Comment by huei90** [comment]
I have no answer yet, as I said above, this is a change in angularjs1.2 => angularjs1.3

Do you have any idea or suggestion to fix it? @obender

**Comment by obender** [comment]
Nope , Investigating ... :-) 
I am long time into java-script more than 6 years but a bit new with angular so it will take a bit time....

**Comment by huei90** [comment]
sure :beers:

**Comment by chenli1989** [comment]
Many thanks

**Comment by huei90** [comment]
I'm not focus on this fix now. Sorry for the inconvenient.

**Comment by a346721573** [comment]
需要用在指令上时，貌似失效了，支持么？

**Comment by huei90** [comment]
目前不支援哦！請升級至 1.3 或 1.4！

**Comment by alanerzhao** [comment]
angular datepicker 貌似报错。
Bootstrap DatePicker
$compile:multidir Multiple Directive Resource Contention

**Comment by hueitan** [comment]
I will drop this issue as moving to the latest version or even AngularJS2 having higher priority than staying around 1.2.
