### ISSUE TITLE
Ticket and Enhancement

### ISSUE THREAD

**Issue by hueitan** [hueitan/angular-validation#174]
This is the list of enhancements:

| Priority | Subject | Assignee | Progress |
| :-: | --- | --- | --- |
| High | Update API Documentation | @huei90 |  |
| Medium | Support i18n | @nazanin1369 | Using `$compile` |
| Medium | Prepare for upcoming AngularJs 2.0 |  | Pending ... |
| Medium | Coverage 100% | @huei90 | Working on. |
| Medium | Update readme - why angular-validation | @huei90 | Working on. |
| Low | Support ng-repeat in angular-validation version 1.2.x #139 |  | Pending ... |
| Low | Make a logo and put it into the README.md |  | Pending ... |
| Low | Rewrite everything in ES6 or Typescript (Optional) |  | Pending ... [#](https://github.com/huei90/angular-validation/issues/170) |
| Low | Support gulp or npm run |  | Pending ... [#](https://github.com/huei90/angular-validation/issues/169) |

DONE LIST

| Priority | Subject | Assignee | Progress |
| :-: | --- | --- | --- |
| High | Support checkbox and radio button (#40) | @lvarayut | Done [#](https://github.com/huei90/angular-validation/pull/175) |
| Medium | callback specification | @huei90 | Done [#](https://github.com/huei90/angular-validation/issues/173) |
| Medium | Coverage support | @huei90 | Done [#](https://github.com/huei90/angular-validation/commit/a18cb3fa8f5eb3861881ca324131504f262c2689) |

**Comment by huei90** [comment]
I have just added one High Priority in **Update API Documentation**

Currently documentation.md is not very clear, we are difficult to find out what we need, this situation same to new user.

I wish we can have a navigation/achor_link so that people can easily find the solution.

**Comment by hueitan** [comment]
I will close this ticket as it is old and open a new ticket if needed.
