### ISSUE TITLE
Add support for dynamic error messages based on attributes

### ISSUE THREAD

**Issue by PachowStudios** [hueitan/angular-validation#181]
Instead of the default error and success messages only being defined statically, setDefaultMsg should allow the error messages to be functions that accept the same parameters that a validation expression does.

For example, you should be able to do this:

``` js
$validationProvider
  .setExpression({
    foo: function(value, scope, element, attrs) {
      return value === attrs.validfoo;
    }
  })
  .setDefaultMsg({
    foo: {
      error: function(value, scope, element, attrs) {
        return 'Foo must equal ' + attrs.validfoo;
      }
    }
  });
```

Instead, you have to use this workaround:

``` js
$validationProvider.setExpression({
  foo: function(value, scope, element, attrs) {
    $validationProvider.setDefaultMsg({
      foo: {
        error: 'Foo must equal ' + attrs.validfoo;
      }
    });

    return value === attrs.validfoo;
  }
});
```

This has the downside though of not showing the error message if the first value entered is invalid.

**Comment by huei90** [comment]
good idea, I will take a look of this feature. Thanks :+1:

**Comment by hungdoan2** [comment]
Actually, all function relate to `error message` must receive full parameter: element, attrs. It will help us alot. 

This morning, I meet a requirement like your. 
I'm going design the API like this `(Implement 1)`: 
```javascript

 $validationProvider.setDefaultMsg({
	required: {
		error: function(element, attrs){
			return attrs.alt + ':' + 'Do not leave it empty!'
		}		
	}
  });
````
But my project require to add `attrs.alt` to ErrorMsg in every validator.Finally, to save my time I decided to do like this`(Implement 2)`: 
```javascript
   $validationProvider.setErrorHTML(function(msg, element, attrs){
		return attrs.alt + ':' + 'Do not leave it empty!';
   });
````

I think both `(Implement 1)` or `(Implement 2)`  are good in particular case, and they will improve the `flexible` of `angular-validation`.

Here is my implement(already in production) : https://github.com/hungdoan2/angular-validation/commit/d0c0a963edb3cec6ec2b9e1f9756c8b0ca970ad5

**Comment by huei90** [comment]
Thanks @hungdoan2 for your Implement1 or 2 suggestions. Both are alright.

**Comment by kushal555** [comment]
@hung-doan  Hey I am trying your solution which is provided above, but in my case, it returns the full string instead of the message. 
Like 
`function(element, attrs){
            return attrs.alt + ':' + 'Do not leave it empty!'
        }`
and its attached to message directly.

**Comment by huei90** [comment]
@kushal555 I don't get your point.

**Comment by kushal555** [comment]
Actually you provided above code 
```
$validationProvider.setDefaultMsg({
    required: {
        error: function(element, attrs){
            return attrs.alt + ':' + 'Do not leave it empty!'
        }       
    }
  });
```

So Sir I am using this code to override the default message and set it for all the required type of validation, but it treats error function value as the string and shows the message completely like 
`function(element, attrs){ return attrs.alt + ':' + 'Do not leave it empty!' }` as below of my input box.
but what I am expecting using that function is that it return string error message like 
`First Name: Do not leave it empty!`.
Sorry, actually my English is not good enough.

**Comment by huei90** [comment]
Hi @kushal555 , unfortunately, the `Function` is only supported in setExpression, setDefaultMsg accepts only String.

This is what the first comment said.

**Comment by huei90** [comment]
We have this feature in PR https://github.com/huei90/angular-validation/pull/198

but we haven't pulled it yet.

**Comment by codeuniquely** [comment]
I was about to ask an issue to ask if this was possible, i was using your own documentation as an example, of expecting a range of inputs ..  Cool Library by the way :)

Example:
```
$validationProvider
  .setExpression({
    range: function(value, scope, element, attrs) {
      if (value >= parseInt(attrs.min) && value <= parseInt(attrs.max)) {
       return value;
      }
    }
  })
  .setDefaultMsg({
    range: {
      error: 'Values should between 5 ~ 10',    // if I pass  in 1 and 12 - message is wrong
      success: 'good'
    }
  });
}])
```

but If we had access to the attributes used we could set the validation error message correctly based on the what was actually used to validate.

```
$validationProvider
  .setExpression({
    range: function(value, scope, element, attrs) {
      if (value >= parseInt(attrs.min) && value <= parseInt(attrs.max)) {
       return value;
      }
    }
  })
  .setDefaultMsg({
    range: function(attrs) {
      error: 'Number should between parseInt(attrs.min) ~ parseInt(attrs.max)',
      success: 'good'
    }
  });
}])
```

Anyway looks like you have it all under control - any ETA on when the PR will be pulled into the build, so i can include the much needed functionality ?

**Comment by scottadamsmith** [comment]
@codeuniquely Sorry, I'm the worst. Working on getting this PR buttoned up so it can be pulled in, and only almost a year later!

**Comment by hueitan** [comment]
Congratulation!! The feature is up now! 🍻 @scottadamsmith Thanks for your contribution.
