### ISSUE TITLE
Improve documentation page with more detailed examples

### ISSUE THREAD

**Issue by joseluisq** [hueitan/angular-validation#191]
I saw your [Examples](http://huei90.github.io/angular-validation/#examples) section in your page and I think you could to improve. 

So here some suggested examples:
- [ ]  Validation examples with multiple forms.
- [ ]  Validation examples for groups of select controls. For example for a birthday field with three selects inline.
- [ ]  Example for hide "valid" message by default. [Now valid messages are shown by default.](https://github.com/huei90/angular-validation/issues/190)

Ref: https://github.com/huei90/angular-validation/issues/164

**Comment by huei90** [comment]
Thanks @joseluisq Currently I'm working on redesign the API documentation and I will include your suggestions into it. 

Thanks again :+1:

**Comment by joseluisq** [comment]
Fantastic !
I will wait for this :+1:

**Comment by huei90** [comment]
If you have any other comments, please let me know :smile:

**Comment by Sunjay999** [comment]
How to check valid form then it should take to next page (action)?
Could you please help me

**Comment by Sunjay999** [comment]
I found this from some of the conversation it is working for me
Thanks :)
.success(function(){
				 window.location = "http://www.google.com"
    })

**Comment by hueitan** [comment]
Close, redesign of the API document has higher priority now.
