### ISSUE TITLE
Form submits only with button click? Not on <enter> within a field. Also ng-submit

### ISSUE THREAD

**Issue by poppahorse** [hueitan/angular-validation#247]
So there seem to be a few issues submitting forms.

I can only attach the submit to an `ng-click` on a button, and when I press enter it doesn't get caught.

Ideally I want to use `ng-submit` to declare the function that should be fired, and able to submit via enter OR pressing the submit button. Both ways of submitting should be blocked by the validation.

https://plnkr.co/edit/nwTEuxuTMmpEc4hrFwGp?p=preview

Without entering anything, you can hit enter, and the `submitYo` function is fired regardless of validation status.

Also when ensuring the form validates, hitting the button will only run the click event, not the one specified on form submit.

Any ideas?

**Comment by huei90** [comment]
What you can do is updating the button type to `type=button`

**Comment by poppahorse** [comment]
Thanks for the response. And `ng-submit` is coming at some point? :)

Yeah ended up doing that, but then put the function + valid check in ng-submit too, feels a bit hacky though but can't guarantee someone is going to actually 'click'

**Comment by huei90** [comment]
nice, do you want to add your solution into [Q&A section](https://github.com/huei90/angular-validation/blob/master/Q%26A.md)?

So that people can benefit from it.
