### ISSUE TITLE
how to reset form from controller?

### ISSUE THREAD

**Issue by fplini** [hueitan/angular-validation#256]
Hi! Is there a way to reset the form from the controller (after some checks)?

**Comment by huei90** [comment]
hi @fplini you can write your own function with the `reset` method.
https://github.com/huei90/angular-validation/blob/master/API.md#reset-the-specific-form-reset

**Comment by alejandro485** [comment]
Hi, the service for reset into controller is `$validation` (from module `validation`) and his receives form tag element in `$validation.reset(Form)`.

**Comment by hueitan** [comment]
Thanks @alejandro485 🍻
