### ISSUE TITLE
Is initial-validity broken?

### ISSUE THREAD

**Issue by rakeshgudipudi** [hueitan/angular-validation#257]
I tried adding initial-validity to an input element. But it was always false. 
I had a look into the source code and figured it was set from scope. But, i guess it had to be initialized from attrs.

The following fixed it for me. 
var initialValidity=attrs.initialValidity;

Let me know if i am on right track or is there a solution without changing source.
Thanks

**Comment by huei90** [comment]
yes @rakeshgudipudi you are right, it should set as `attrs`, I don't even remember why we set it as scope 👍 

Thanks anyway!!!

@lvarayut Do you have any thought here?

**Comment by huei-tan-sociomantic** [comment]
Finally, it is because we already remove the scope in defining the directive here
https://github.com/huei90/angular-validation/blob/master/src/validator.directive.js#L265

@rakeshgudipudi Do you mind creating a PR for this?

**Comment by huei90** [comment]
Finally, it is because we already remove the scope in defining the directive here
https://github.com/huei90/angular-validation/blob/master/src/validator.directive.js#L265

@rakeshgudipudi Do you mind creating a PR for this?
