### ISSUE TITLE
form group/groups

### ISSUE THREAD

**Issue by burhanfarooqws** [hueitan/angular-validation#270]
Hi,

can I use more than one form group on one element.
my page actually need this kind of feature like nested form child form has limited element with parent form add more element but on parent submit I need to make sure child form is also valid.

any idea if this is possible?

**Comment by huei90** [comment]
have you tried `validation-group={scope}`, update the scope when you click the different button.

**Comment by burhanfarooqws** [comment]
![screenshot_20170115-150746](https://cloud.githubusercontent.com/assets/17730402/21961768/eddf1f48-db34-11e6-930b-d88a46cdb65b.png)

Here is my screen, the child form has fields but OTP field is not required as for send otp click the value is fetched & put by user .... but on register click i need to validate all fields .... kind of confuse how to achieve it .... 

Thanks

**Comment by huei90** [comment]
@lvarayut do you have any idea of using validation-group here?

**Comment by lvarayut** [comment]
I'm not quite sure if I understand the question correctly. Based on the provided example, all fields are marked as "*" indicating mandatory fields. Couldn't we just use a normal `validator="required"` when a user click on the Register button?

**Comment by burhanfarooqws** [comment]
The use case is when user click send OTP button the OTP field should not be validated as its a server call which generate password send to user on email.
then user put it in the OTP field now user can re-send OTP if he wants.
When user click register button the OTP must be validated kind of conditonal required but form submit is trouble in this when use ng-required conditional.

What should be my approach.?

**Comment by lvarayut** [comment]
In this case, I think we might need some kind of condition to make OTP field optional. Could you take a look at #152 and #229?
