### ISSUE TITLE
Compare the value of 2 inputs

### ISSUE THREAD

**Issue by johnnytn** [hueitan/angular-validation#273]
Can I compare 2 fields? Something like `password` must have the same value of `cofirmPassword`.
I know i can create my custom validator, but how can I do something like this?
`validator="checkValue=customValue`

I've already tried passing `{{user.password}}`

**Comment by hueitan** [comment]
Is this the password validator you are looking for?
https://github.com/hueitan/angular-validation/issues/24#issuecomment-47635437

**Comment by johnnytn** [comment]
Well if the this validator compare 2 values then yes 😅 .
If not I got a workaround passing `checkSameValue={{user.password}}` and then splitting the `attrs.validator`

**Comment by hueitan** [comment]
Do you mind show the example why you need to compare 2 fields in one validator?

**Comment by johnnytn** [comment]
Well I need to compare 2 values, cuz I want both values to be the same.

**return value1 == value2**

**Comment by hueitan** [comment]
> Well I need to compare 2 values, cuz I want both values to be the same.

Isn't this same as the password validation?

**Comment by johnnytn** [comment]
And how do I use this `password` validator ? I didn't saw it in the Documentation APi

**Comment by hueitan** [comment]
You can use the example given in the comment. https://github.com/hueitan/angular-validation/issues/24#issuecomment-47635437

**Comment by johnnytn** [comment]
@hueitan  ty for a better solution. I was doing like this, but It was not that clean
```javascript
     sameValue: function (value, scope, element, attrs, param) {
            var validatorValue = attrs.validator;
            validatorValue = validatorValue.split('=');
            return value == validatorValue[1];
        }
```
