### ISSUE TITLE
The require validation conflict with the min and max

### ISSUE THREAD

**Issue by gaojianzhuang** [hueitan/angular-validation#274]
Sometimes we just want to use the min or max validation, but the angular-validation need the "required" validation first, it is not our expected.
How do we need to change the logic?

**Comment by hueitan** [comment]
Please read the document and learn how to use rule

**Comment by kushal555** [comment]
Hello @hueitan,
I read complete document and didn't get any case which describes how to put only min and max without required method.

In my case when I put the min=10,max=15 and if the user clicks on that element the validation message fired for min length. If we remove complete data from element then also validation message fired for min length as well.

Please let me know what is the proper way to user min and max without required

Thank you.

**Comment by kushal555** [comment]
Hello @gaojianzhuang 
If you find any alternate then Please provide me here.

**Comment by hueitan** [comment]
> put only min and max without required method.

you need to customize your expression.

if you are using below expression, means you are required the user to input at least something, you need to customize it and **allow passing empty value**.

```js
range: function(value, scope, element, attrs) {
    if (value >= parseInt(attrs.min) && value <= parseInt(attrs.max)) {
        return value;
    }
}
```

**Comment by kushal555** [comment]
@hueitan Than you very much for your instant support.

I really appreciate your work.
