### ISSUE TITLE
API文档getMsgElement示例异常

### ISSUE THREAD

**Issue by chensiyao** [hueitan/angular-validation#277]
**## API文档的getMsgElement使用示例有异常。下图为示例代码**

![tl 20170221175957](https://cloud.githubusercontent.com/assets/17638288/23159927/98646f1c-f85f-11e6-9887-ed79e4089fc6.png)

    源码中有一段为: messageElem.html('').append(
                $compile($validationProvider.getErrorHTML(messageToShow, element, attrs))(scope));

    在使用zepto时, 上图中messageElem对象的类型为zepto对象的实例。
    $compile(...)(scope)编译后的对象为angular.element()对象，
    在执行zeptoEle.append(angularEle)方法时会报错。
    
    示例中getMsgElement返回的对象应该为 angular.element( $(element).parent().children().last() );

**Comment by hueitan** [comment]
This is just an example, you are free to modify/create the method by yourself.
