### ISSUE TITLE
Validation=required not working in select2

### ISSUE THREAD

**Issue by ycpatel813** [hueitan/angular-validation#279]
Hi 
I found your directive and i am very much happy to use this validator but i have used select2 controll also and validator not working `Validation=required` not working in select2.

Please suggest me some instruction.
Thanks in advance.

**Comment by hueitan** [comment]
Hi @ycpatel813 sorry for the late reply.

Do you mind try this solution?
https://github.com/hueitan/angular-validation/issues/61#issuecomment-65266045

**Comment by kushal555** [comment]
Hello @hueitan,
I read complete document and didn't get any case which describes how to put only min and max without required method. 

In my case when I put the ``min=10,max=15`` and if the user clicks on that element the validation message fired for min length. If we remove complete data from element then also validation message fired for min length as well. 

Please let me know what is the proper way to user min and max without required 

Thank you.
