### ISSUE TITLE
Question: How to re-call validation on a single form input ?

### ISSUE THREAD

**Issue by codeuniquely** [hueitan/angular-validation#280]
I already use checkValid to make calls to see if the form is valid when the form is submitted, enabling me to highlight any missed or invalid inputs when the user tries to submit the form. The individual form inputs have validator rules and use ngMessages to render individual input errors

But I have a requirement to be able to update a value in the form and validate a related input that may have already been provided. (i.e. the user goes back up the form and alters a previously entered value, which was used to calculate the string for the validator on another inputs in the form.

i.e
```
Number of People who share [ 3 ]
Amount of items to be shared by these people [ 6 ]
```
n.b.
_The validation checks that the number of items is an exact multiple of the number of people._

so the example above is valid - but if the user now changed the number of people to 4 then the validation on the items field needs to fail and display the error message ....

The customers requires are that other items on the form cannot be invalidated until the user has enter values for them (and blur's out of the field) or that the user hits the submit button - in which case the form validates and ALL error messages are shown .....

So i have a requirement to programatically run the validation on one input based on another inputs value changing and then (because that field wont have focus (it will have been blur'd and will be $dirty) - the standard error message functions should kick in ....

something like
```
// re-run validation on the 'items' property in form  form['items'] or form.items .... ????
this.$validationProvider.checkValidInput(form, 'items');  
```

**Comment by hueitan** [comment]
You can manually call the validate API by using

```js
this.$validationProvider.validate( form )
```

**Comment by codeuniquely** [comment]
Ye si know you can call that and i do when the user hits SUBMIT, but that call validates the entire form - causes all inputs on the form to have their validation checked and any associated messages will be fired and shown in the UI.  

This is not what I asked: 

What I asked, was for was way to validation just a single input:  

There is a UX business case with my customer that requires:
That ONLY validation on the effected control, related to the input entered (which now causes that previous entry to be invalid) MUST be shown. All other validation messages not related to that changed input MUST NOT display ANY validation messages.

I know the related fields and i want to trigger the validation to fire on the related input ONLY, not the whole form.

**Comment by hueitan** [comment]
yes, you can validate only single on input

```html
<form name="Form">
    <input type="text" name="required" ng-model="required" validator="required"/><input type="text" name="required2" ng-model="required2" validator="required"/>
</form>

<script>
// ...
validationProvider.validate($scope.Form.required)
// ...
</script>

**Comment by codeuniquely** [comment]
Sorry but just to be sure,

You can validate a given named input (covered by validation rules)

i.e.
````
if ( input_needs_validation && form && input_name) {
    let input = form[input_name];
    validationProvider.validate( input );
}

**Comment by hueitan** [comment]
Yes you can!

**Comment by codeuniquely** [comment]
OK cool - then we can close this - because that exactly what I need 

:)

**Comment by hueitan** [comment]
Perfect 👍
