### ISSUE TITLE
npm 1.4.3 package contains file with no name - breaks install

### ISSUE THREAD

**Issue by peet** [hueitan/angular-validation#281]
```
npm ERR! tar.unpack untar error C:\Users\me\AppData\Roaming\npm-cache\angular-validation\1.4.3\package.tgz
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! path C:\Users\me\git\app\node_modules\.staging\angular-validation-77491ba8
npm ERR! code EEXIST
npm ERR! errno -4075
npm ERR! syscall mkdir

npm ERR! EEXIST: file already exists, mkdir 'C:\Users\me\git\app\node_modules\.staging\angular-validation-77491ba8'
npm ERR! File exists: C:\Users\me\git\app\node_modules\.staging\angular-validation-77491ba8
npm ERR! Move it away, and try again.
```

This is caused by a file with no name being included in the 1.4.3 tgz downloaded from npm, which isn't present in the 1.4.2 tgz. This should be fixable by republishing to npm, after ensuring the directory is clean.

**Comment by peet** [comment]
The file contents, to help understand where it came from, is the commit message template:
```

Bump version v1.4.3
# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
# On branch master
# Your branch is up-to-date with 'origin/master'.
#
# Changes to be committed:
#	modified:   CHANGELOG.md
#	modified:   README.md
#	modified:   bower.json
#	modified:   package.js
#	modified:   package.json
#
```

**Comment by hueitan** [comment]
> npm ERR! Move it away, and try again.

Hi @peet Sorry for the late response, have you tried what NPM said?

**Comment by peet** [comment]
The file that NPM is complaining about is the directory the tar is expanding into. When it tries to extract the no-name file, it ends up with the same path name, so refuses to write it, causing the error. The directory doesn't exist before or after the command, as it's only temporary for the extraction.

You can download the tgz file from npm to inspect with `npm pack angular-validation@1.4.3`

**Comment by hueitan** [comment]
Hi @peet I will publish a version 1.4.4 for the latest changes in these few days or next week. after that, you can try install it again.

**Comment by peet** [comment]
Great, I'm sure that will fix it. I'll reopen this if it is somehow still broken :)

**Comment by peet** [comment]
Hi @hueitan, 1.4.3 is gone from npm, but we still need its bugfixes over 1.4.2.

Can you please publish 1.4.4 soon?

**Comment by hueitan** [comment]
Thanks, I will publish 1.4.4 soon, at the moment, do you mind using `#master` for your project?

**Comment by hueitan** [comment]
version 1.4.4 has been published! thanks for the waiting!
