### ISSUE TITLE
How to set input invalid using controller

### ISSUE THREAD

**Issue by syiwawahyu** [hueitan/angular-validation#282]
Hello, is there anyway to make form input invalid from controller? Because, i have response from server that return validation message too and i want to append server validation message to form input through your package. Thank you before.

**Comment by hueitan** [comment]
use $promise

**Comment by syiwawahyu** [comment]
Ok, let's say i have variable $scope.name , it's a model for form input text. The user input it right, but i want to make it invalid from controller. So, what i must doing in $scope.name? Can you give me example please. Thanks before

**Comment by hueitan** [comment]
I think you need somehow kind of **pending validation**. Unfortunately, angular-validation provides only `valid` and `invalid` state validation, there is no such kind of between validation.

you might need to find out a way to hack for this between validation.

one suggestion example you can try

```js
$scope.submitForm = function( Form )
{
    // before trigger request to server
    // trigger( 'pending state' )
    ...your request
    // in response scope
    // remove the pending state
}
```
