### ISSUE TITLE
关于validation-group的疑问

### ISSUE THREAD

**Issue by star-hope** [hueitan/angular-validation#284]
如果用于login校验，所有的校验失败的结果都指定到span元素，请问要怎么设置才能让第一个校验失败信息的展示在元素上，比如有用户名输入框，密码输入框，验证码输入框，我什么都不填写直接点击登录按钮，理论上应该是显示请输入用户名的提示才对，但是显示了请输入验证码的提示了

**Comment by hueitan** [comment]
Hi @star-hope sorry for the late reply.

please check again the [api documentation page](https://github.com/hueitan/angular-validation/blob/master/API.md), and follow the intrusction building a valid Form and it's validation configuration.

reopen if needed
