### ISSUE TITLE
Need to Add equalTo validation as it's required and widely used too. 

### ISSUE THREAD

**Issue by tomavic** [hueitan/angular-validation#289]
Need to add equalTo() validation method as like in jquery validtion library
```
// https://jqueryvalidation.org/equalTo-method/
equalTo: function( value, element, param ) {
	var target = $( param );
	if ( this.settings.onfocusout && target.not( ".validate-equalTo-blur" ).length ) {
		target.addClass( "validate-equalTo-blur" ).on( "blur.validate-equalTo", function() {
			$( element ).valid();
		} );
	}
	return value === target.val();
}
```

**Comment by hueitan** [comment]
you are free to add any library as you like in your application. 😄

**Comment by tomavic** [comment]
yes I know that very well :) but It would be better if you added this to your library as there is many DEVs are using it. Consider it as a part of making your library powerfull!

**Comment by hueitan** [comment]
no worry, every awesome developer can add any feature in their application. I want to keep this library as clean as possible and avoid those user preference third/support library.
