### ISSUE TITLE
Required validation is invalid when model value is 0

### ISSUE THREAD

**Issue by brabao** [hueitan/angular-validation#290]
Required validation is invalid when model value is 0

[https://embed.plnkr.co/Qmlp3W/](https://embed.plnkr.co/Qmlp3W/)

**Comment by hueitan** [comment]
This is expected since you are using `required` validation and the model is given `integer`

you either

1. makes the model to be string integer "0" "1" "2" "3" ...
1. not using required, but using the validation number >= 0

**Comment by brabao** [comment]
I send pull request (#291) to fix it
thanks
