### ISSUE TITLE
I´m getting the error Possibly unhandled rejection: error

### ISSUE THREAD

**Issue by bbasura16** [hueitan/angular-validation#294]
when submit , get the error in console Possibly unhandled rejection: error
when call  $validationProvider.checkValid($scope.Formname) always  is false, even when all inputs are ok.
Any help?, thank you

**Comment by huei-tan-sociomantic** [comment]
you need to validate to get the validation before calling checkValid.

**Comment by hueitan** [comment]
you need to validate to get the validation before calling checkValid.

**Comment by bbasura16** [comment]
Hello
I do the next steps:
$validationProvider.validate($scope.Formname);
--later:
$validationProvider.checkValid($scope.Formname)
the lastone, always is false.

**Comment by bbasura16** [comment]
Sorry, I was validating a select2 with custom error, and it doesnot show error , I found this i fix. Thanks for you time.
