### ISSUE TITLE
720kb datepicker is not working when we include angular-validation inside it.

### ISSUE THREAD

**Issue by gauravBrain** [hueitan/angular-validation#296]
i am using 720kb date picker.when i include validatior="required"  in the input feild inside the date picker then datepicker stops working..

**Comment by hueitan** [comment]
I believe the datepicker is working but you need to setup and integrate with angular validation.

This is one of the example that if you want to integrate angular validation with Bootstrap
https://github.com/hueitan/angular-validation#integrating-with-twitter-bootstrap

**Comment by gauravBrain** [comment]
i have tried this but its not working....
this is the code

`<datepicker date-format="yyyy-MM-dd" selector="form-control">
                        <div class="form-group">
                          <input type="text" class="form-control" placeholder="DATE"  ng-model="$ctrl.itemContent.date" name="date" validator="required">
                        </div>
                </datepicker>
             `

**Comment by gauravBrain** [comment]
on clicking the input box date picker calender is not opening..

**Comment by hueitan** [comment]
Sorry for the late reply.

Can you try using a Form element to wrap your code?

```Html
<form name="myForm">
   <yourcode/>
</form>
```

**Comment by hueitan** [comment]
Please reopen or create the issue if this is not working.
