### ISSUE TITLE
how can use with angular ui select 

### ISSUE THREAD

**Issue by fatiheng** [hueitan/angular-validation#300]
can I get an example about using with angular ui select ?

**Comment by hueitan** [comment]
here's the example code from the demo page

https://github.com/hueitan/angular-validation/blob/c2751965228702b8f9015755ac206c0d58f09afd/index.html#L405-L442

**Comment by fatiheng** [comment]
Thanks a lot.

**Comment by hueitan** [comment]
let me know if this is not useful to you.
