### ISSUE TITLE
Allow empty string for validator?

### ISSUE THREAD

**Issue by AKolodeev** [hueitan/angular-validation#302]
Hi, @hueitan,

Sometimes I need to pass empty validator depend on condition:
```html
<input name="someField"
            ng-model="$ctrl.someFieldValue"
            validator="{{ $ctrl.someOtherFieldValue ? 'required' : '' }}">
```
I can not do this now because of `angular-validation.js:575 You are using undefined validator ""` error.

I can solve this issue either by creating two `input` elements:
```html
<input name="someField"
            ng-if="$ctrl.someFieldValue"
            ng-model="$ctrl.someFieldValue"
            validator="required">
<input name="someField"
            ng-if="$ctrl.someFieldValue"
            ng-model="$ctrl.someFieldValue">
```
or if angular-validation will handle empty\undefined validator.

If you don't mind I'll fix this behavior and create PR.

**Comment by hueitan** [comment]
In my opinion, empty validated shouldn't activate valuation.
PR is always welcome :beers:
