### ISSUE TITLE
Clear Form after submit shows validation

### ISSUE THREAD

**Issue by sanujgandhi** [hueitan/angular-validation#304]
Hi, 

I am trying to clear the form after saving or updating the data, but It shows the validations messages when I empty the object from controller. Please let me know how to empty the fields and make form as new to fill again.

Thanks,
Sanuj

**Comment by hueitan** [comment]
Try using the reset method
https://github.com/hueitan/angular-validation/blob/master/API.md#reset-the-specific-form-reset

**Comment by sanujgandhi** [comment]
I am getting error unknown validationprovider when using in controller. Following is my Controller method and Html. Please have a look.

 $scope.saveCompany = function (form) {
            $scope.company.FirmTypeId = 1;
            $scope.company.IsActive = true;
            companyService.saveCompany($scope.company).then(function (response) {
                  $scope.company = {};
                //validationProvider.reset(form);
                //$scope.resetCompany();
                $('#update-data').modal('toggle');
            });
        };



-----------------------------------------------------------------------------------------------------------------
<form name="updateCompanyForm" class="form-horizontal">
                            <div class="row">
                                <div class="col-md-12">
                                        <div class="form-group">
                                        <label class="col-md-3 control-label">{{'CompanyName' | translate}}:</label>
                                        <div class="col-md-9">
                                            <input ng-model="company.Name" name="company" validator="required" placeholder="name" type="text">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="col-md-12 text-right">
                                            <button ng-show="AddCompany" type="submit" ng-click="saveCompany(updateCompanyForm)" validation-submit="updateCompanyForm" class="btn btn-sm btn-success">{{'Save' | translate}}</button>
                                                       </div>
                                    </div>
                                </div>
                            </div>
                        </form>

**Comment by sanujgandhi** [comment]
Hi Please help me in this issue as I am not able to reset form in controller.

**Comment by sanujgandhi** [comment]
It Works using var $validationProvider = $injector.get('$validation');
 Thank you very much for your time. 👍  

Regards,
Sanuj
